//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public module_group()
        {
            this.module_detail = new HashSet<module_detail>();
        }
    
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string title { get; set; }
        public string title_us { get; set; }
        public string url { get; set; }
        public Nullable<int> idmenu { get; set; }
        public Nullable<int> showhome { get; set; }
        public string des { get; set; }
        public string keyword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<module_detail> module_detail { get; set; }
        public virtual module_menu module_menu { get; set; }
    }
}
