//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_sanphamLogs
    {
        public long Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
        public double StockTotal { get; set; }
        public double StockTotalAll { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual shop_sanpham shop_sanpham { get; set; }
        public virtual SoftBranch SoftBranch { get; set; }
    }
}
