//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shop_sanpham()
        {
            this.shop_bienthe = new HashSet<shop_bienthe>();
            this.shop_collection = new HashSet<shop_collection>();
            this.shop_image = new HashSet<shop_image>();
            this.sys_bangtin_conhang = new HashSet<sys_bangtin_conhang>();
            this.support_cauhoi = new HashSet<support_cauhoi>();
            this.shop_sanphamLogs = new HashSet<shop_sanphamLogs>();
            this.SoftAdjustmentStockDetails = new HashSet<SoftAdjustmentStockDetail>();
            this.SoftBranchProductStocks = new HashSet<SoftBranchProductStock>();
            this.SoftChannelProductPrices = new HashSet<SoftChannelProductPrice>();
            this.SoftOrderDetails = new HashSet<SoftOrderDetail>();
            this.SoftReturnSupplierDetails = new HashSet<SoftReturnSupplierDetail>();
            this.SoftStockInDetails = new HashSet<SoftStockInDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string masp { get; set; }
        public Nullable<int> maloai { get; set; }
        public Nullable<int> mahieu { get; set; }
        public Nullable<int> plantype { get; set; }
        public string tensp { get; set; }
        public string tensp_us { get; set; }
        public Nullable<int> typeshowhome { get; set; }
        public string thongtin { get; set; }
        public string thongtin_us { get; set; }
        public string spurl { get; set; }
        public string spurl_us { get; set; }
        public string sptitle { get; set; }
        public string sptitle_us { get; set; }
        public string spdescription { get; set; }
        public string spdescription_us { get; set; }
        public string spkeywords_us { get; set; }
        public string spkeywords { get; set; }
        public Nullable<bool> hide { get; set; }
        public string chitiet { get; set; }
        public string chitiet_us { get; set; }
        public Nullable<int> douutien { get; set; }
        public Nullable<bool> ischeckout { get; set; }
        public Nullable<bool> ischecksaleoff { get; set; }
        public Nullable<bool> ischeckgift { get; set; }
        public string gift { get; set; }
        public Nullable<int> countsale { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
        public Nullable<double> kg { get; set; }
        public Nullable<double> chieudai { get; set; }
        public Nullable<double> chieurong { get; set; }
        public Nullable<double> chieucao { get; set; }
        public Nullable<double> chieudaisd { get; set; }
        public Nullable<double> chieurongsd { get; set; }
        public Nullable<double> chieucaosd { get; set; }
        public Nullable<bool> showkg { get; set; }
        public Nullable<bool> showcm { get; set; }
        public Nullable<bool> showhome { get; set; }
        public Nullable<bool> showbanner { get; set; }
        public Nullable<bool> showsptangkemvaomuckm { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> StopSale { get; set; }
        public Nullable<int> PriceBase { get; set; }
        public Nullable<int> PriceBaseOld { get; set; }
        public Nullable<int> PriceAvg { get; set; }
        public Nullable<int> PriceWholesale { get; set; }
        public Nullable<int> PriceRef { get; set; }
        public Nullable<bool> freeship { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string StatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> NotDiscountMember { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FromCreate { get; set; }
        public Nullable<int> ShopeeId { get; set; }
        public Nullable<int> CodeSuffix { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual ApplicationUser ApplicationUser1 { get; set; }
        public virtual shop_showhome shop_showhome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_bienthe> shop_bienthe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_collection> shop_collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_image> shop_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_bangtin_conhang> sys_bangtin_conhang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<support_cauhoi> support_cauhoi { get; set; }
        public virtual shop_sanphamCategories shop_sanphamCategories { get; set; }
        public virtual shop_sanphamStatus shop_sanphamStatus { get; set; }
        public virtual SoftSupplier SoftSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop_sanphamLogs> shop_sanphamLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftAdjustmentStockDetail> SoftAdjustmentStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftBranchProductStock> SoftBranchProductStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftChannelProductPrice> SoftChannelProductPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftOrderDetail> SoftOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftReturnSupplierDetail> SoftReturnSupplierDetails { get; set; }
        public virtual shop_thuonghieu shop_thuonghieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftStockInDetail> SoftStockInDetails { get; set; }
    }
}
