//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftStockInDetail
    {
        public int StockInId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PriceNew { get; set; }
        public Nullable<int> PriceRef { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual shop_sanpham shop_sanpham { get; set; }
        public virtual SoftStockIn SoftStockIn { get; set; }
    }
}
