//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoftOrder()
        {
            this.SoftOrderDetails = new HashSet<SoftOrderDetail>();
        }
    
        public int Id { get; set; }
        public int BranchId { get; set; }
        public int ChannelId { get; set; }
        public string Serial { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<bool> DiscountFive { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<int> DiscountTotal { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<long> Total { get; set; }
        public Nullable<long> CustomerPaid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string StatusId { get; set; }
    
        public virtual SoftBranch SoftBranch { get; set; }
        public virtual SoftChannel SoftChannel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftOrderDetail> SoftOrderDetails { get; set; }
        public virtual SoftOrderStatu SoftOrderStatu { get; set; }
    }
}
