//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBBM.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftPointUpdateLog
    {
        public long Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> PointAdd { get; set; }
        public Nullable<int> PointBefore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual donhang donhang { get; set; }
    }
}
